### ISSUE TITLE
Merge with oc-template-handlebars

### ISSUE THREAD

**Issue by nickbalestra** [opencomponents/base-templates#16]
Due to the many shared packages that both legacy templates (`jade` and `handlebars`) rely on, Is advised to merge them both together and rename this repo into `base-templates` so that development on each template together with work needed on any shared package (webpack configurator, infinite-loop-loader,...) will be more accessible and publishing will require way less efforts. Nonetheless we already have a lerna structure on both, so the transaction will be seamless

**Comment by matteofigus** [comment]
I would say, go for it. At the moment it really seems like something that could speed up dev.

If it doesn't work, we can re-separate it later.

**Comment by nickbalestra** [comment]
👍  As soon as the jade template is finished, I'll do it so that the handlebars template will be worked in here
