### ISSUE TITLE
Sourcemaps support for infite-loop-loader

### ISSUE THREAD

**Issue by nickbalestra** [opencomponents/base-templates#30]
Moved from https://github.com/nickbalestra/infinite-loop-loader/issues/3

Info:
So that when the loader is in a chain of loaders, the source map properly maps the transformation.

To create sourcemaps, this project seems to be pretty good: https://github.com/mozilla/source-map#generating-a-source-map

Here an example of how to add sourcemaps to falafel (using your suggest source-map) : alltom/node-falafel-map@5b20ef2

**Comment by matteofigus** [comment]
Currently blocked by this: https://github.com/substack/node-falafel/pull/66

**Comment by matteofigus** [comment]
Closing as not needed anymore.
