### ISSUE TITLE
📦:🛠✨💥 – fully automated package publishing with semantic release

### ISSUE THREAD

**Issue by nickbalestra** [opencomponents/base-templates#32]
- [x]  [Commitzen](https://github.com/commitizen/cz-cli)
- [x] [Conventional-changelog](cz-lerna-changelog)
- [x] [Lerna-semantic-release](https://github.com/atlassian/lerna-semantic-release)

**Comment by matteofigus** [comment]
lol reopened 🤣

**Comment by matteofigus** [comment]
- [ ] It actually works
