### ISSUE TITLE
Support CSS-Modules

### ISSUE THREAD

**Issue by nickbalestra** [opencomponents/base-templates#47]
Could be interesting to investigate supporting css-modules for the handlebars and jade templates

- few references for handlebars
  - https://www.npmjs.com/package/interpolate-html-css-modules-webpack-plugin
  - https://github.com/lucasconstantino/handlebars-css-modules-sample

**Comment by matteofigus** [comment]
I think I would love this in the newest ES6 but I don't think I would invest too much efforts on handlebars and jade? My 2 cents :)
